# Generated by Django 4.1 on 2022-09-05 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='perfiles')),
                ('biografia', models.TextField(blank=True, null=True)),
                ('recibemails', models.BooleanField(default=False)),
                ('alumno', models.BooleanField(default=False)),
                ('profesor', models.BooleanField(default=False)),
                ('sexo', models.CharField(default='F', max_length=1)),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
