# Generated by Django 4.1 on 2022-09-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='avatar',
            field=models.ImageField(upload_to='core'),
        ),
    ]
