# Generated by Django 4.1 on 2022-09-06 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_curso_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='curso1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('disciplina', models.CharField(max_length=20)),
                ('avatar', models.ImageField(upload_to='core')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('calificacion', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('alumnos', models.IntegerField(default=0)),
                ('completo', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
