# Generated by Django 4.1 on 2022-09-06 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_curso1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='curso1',
        ),
    ]
