# Generated by Django 4.1 on 2022-09-06 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_curso_disciplina'),
        ('visitante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.TextField()),
                ('nivel', models.CharField(default='m', max_length=10)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
            ],
        ),
    ]
