# Generated by Django 4.1 on 2022-09-07 19:22

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0004_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='core')),
                ('dirurl', models.URLField(blank=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='visitante')),
                ('texto', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitante.tema')),
            ],
        ),
    ]
